<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
name: github pages
=======
name: deploy
>>>>>>> 22b63c338da6698467e806502a86df96ba5138dc
=======
name: deploy
>>>>>>> 8fb632caa891243c1e60c34c855075d13da3e181
=======
name: deploy
>>>>>>> 8fb632caa891243c1e60c34c855075d13da3e181

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run build
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run build
<<<<<<< HEAD
<<<<<<< HEAD
=======
      - run: mv ./CNAME ./build
>>>>>>> 8fb632caa891243c1e60c34c855075d13da3e181
=======
      - run: mv ./CNAME ./build
>>>>>>> 8fb632caa891243c1e60c34c855075d13da3e181
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
